# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

description: |
  Install/configure docker with buildx to
  cross-compile docker images and deploy them

commands:
  recursive-checkout:
    steps:
      - checkout
      - run:
          name: "Checkout submodules"
          command: git submodule update --init --recursive
  update-docker:
    parameters:
      experimental:
        description: "Setting Docker engine and client to experimental"
        type: boolean
        default: true
    steps:
      - run:
          name: "Remove existing Docker installation"
          command: |
            sudo apt-get update -qq
            sudo apt-get remove -y docker-ce docker-ce-cli containerd.io
      - run:
          name: "Install current Docker version and enable experimental features"
          command: |
            <<# parameters.experimental >>
            mkdir $HOME/.docker
            echo -e '{\n    "experimental":"enabled" \n}' | tee -a $HOME/.docker/config.json
            echo -e '{\n    "experimental":true \n}' | sudo tee -a /etc/docker/daemon.json
            <</ parameters.experimental >>
            curl -fsSL https://get.docker.com/ | sudo sh
            sudo usermod -aG docker $(whoami)
  install-qemu:
    parameters:
      url:
        description: "QEMU static conf file for Docker"
        type: string
        default: "https://github.com/computermouth/qemu-static-conf.git"
    steps:
      - run:
          name: "Install QEMU support for multi-architecture builds"
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y qemu qemu-user-static qemu-user binfmt-support
            git clone << parameters.url >>
            sudo mkdir -p /lib/binfmt.d
            sudo cp qemu-static-conf/*.conf /lib/binfmt.d/
  install-buildx:
    parameters:
      url:
        description: "Buildx release page"
        type: string
        default: "https://github.com/docker/buildx/releases"
      version:
        description: "Version of buildx release under << parameters.url >>"
        type: string
        default: "v0.3.1"
      artifact:
        description: "Buildx artifact, which should be used"
        type: string
        default: "buildx-v0.3.1.linux-amd64"
    steps:
      - run:
          name: "Install BuildX plugin for Docker"
          command: |
            curl --output docker-buildx --silent --show-error --location --fail --retry 3 \
              "<< parameters.url >>/download/<< parameters.version >>/<< parameters.artifact >>"
            mkdir -p ~/.docker/cli-plugins
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx


jobs:
  buildx:
    working_directory: ~/docker-gitea
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - recursive-checkout
      - update-docker
      - install-qemu
      - install-buildx
      - run: make

workflows:
  buildx-and-push:
    jobs:
      - buildx:
          filters:
              tags:
                only: /.*/
